import './styles/globals.css'
import { Inter } from 'next/font/google'
import SideBar from './components/sideBar/Sider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Market Place App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + ' flex gap-4 backgroundIMG'}>
        <div className="mainBody w-10/12 p-6 border border-white">
          {children}
        </div>
        <div className="sideBar w-1/5 py-6 border border-white">
          <SideBar />
        </div>
      </body>
    </html>
  )
}
